---
# show-list settings
list:
  default_group: 'term'
  preview_length: 60
  table:
    style: 'fancy'
    index_align: 'right'
    preview_align: 'left'
    time_align: 'left'

# daemon configuration
daemon:
  capture_live: true
  recopy_live: true
  term_backend: 'term'
  live_backend: 'live'
  backends:
    live:
      storage: 'disk'
      expiration: 'reboot'
      min_entries: 1
      max_entries: 5
    wl-clip:
      storage: 'disk'
      expiration: 1200
      min_entries: 1
      max_entries: 5
    default:
      storage: 'disk'
      expiration: 'reboot'
      max_entries: null
